//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WxUser
    {
        public long ID { get; set; }
        public string Wx_id { get; set; }
        public string Wxidcode { get; set; }
        public string wxName { get; set; }
        public string Wxprovince { get; set; }
        public string Wxcity { get; set; }
        public string WxImg { get; set; }
        public Nullable<short> Wxgender { get; set; }
        public Nullable<int> UserInfoID { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
